### ISSUE TITLE
新版dump工具指定时间参数

### ISSUE THREAD

**Issue by SCY-ICT** [taosdata/taos-tools#122]
软件信息：
Tdengine 版本：2.4.0.4
taos-tool版本：1.1.0

系统硬件信息：
Centos7
内存：30G
CPU:Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz

错误描述：
### #!/bin/expect  
set timeout 30 
spawn **taosdump -c /etc/taos/taos.cfg -o /data/taosExportData/temp/a2022-01-27/dynamic -D gc_dynamic_data -S 2022-01-2700:00:00.000+0800 -E 2022-01-2800:00:00.000+0800 -B 100 -T 20**
expect "Enter password: "
send "taosdata\r"
interact

执行此dump语句的时候时间解析有问题
<img width="925" alt="f22ba55d25200bf7135dc0c4956c3bc" src="https://user-images.githubusercontent.com/87170765/151353177-798fc18d-5b79-45b2-a643-7f99c5a713b9.png">

=====================================================================

[root@node1 temp]# expect exportTaosDynamic.sh 
spawn taosdump -c /etc/taos/taos.cfg -o /data/taosExportData/temp/a2022-01-27/dynamic -D gc_dynamic_data -S '2022-01-2700:00:00.000+0800' -E '2022-01-2800:00:00.000+0800' -B 100 -T 20
====== arguments config ======
host: (null)
user: root
password: taosdata
port: 0
outpath: /data/taosExportData/temp/a2022-01-27/dynamic/
inpath: 
resultFile: ./dump_result.txt
all_databases: false
databases: 1
databasesSeq: gc_dynamic_data
schemaonly: false
with_property: true
answer_yes: false
avro codec: snappy
start_time: -9223372036854775806
human readable start time: 2022-01-2700:00:00.000+080 
end_time: 9223372036854775807
human readable end time: 2022-01-2800:00:00.000+080 
precision: ms
data_batch: 100
max_sql_len: 65480
thread_num: 20
allow_sys: 0
abort: 0
isDumpIn: 0
arg_list_len: 0
debug_print: 0

start_time 与endtime 转换的时间有问题吧   2022-01-27T00:00:00.000+0800  这种中间加T的也是这样   包括直接用13位时间戳也会有问题

**Comment by SCY-ICT** [comment]
忽略图片中 starttime与endtime 后面日期两边的 ' 单引号  那个是为了测试加上去的

**Comment by sangshuduo** [comment]
这个问题是调试信息并不准确反映实际执行最后计算出来的时间戳，后面版本会优化调试信息的显示。备份功能没有问题。本 issue 关闭。
