### ISSUE TITLE
taosdump运行报错

### ISSUE THREAD

**Issue by redgreat** [taosdata/taos-tools#367]
安装的是最新2.1.3版面本
系统 CENTOS7.9

运行

```
[root@tdengine1 bin]# taosdump -V
taosdump: symbol lookup error: taosdump: undefined symbol: inflateReset
```
备份报同样错误
```
[root@tdengine1 ~]# taosdump -o /mnt/tdenginebak/ljmtest/instance20220906 -T 4 ljmtest instance --debug
taosdump: symbol lookup error: taosdump: undefined symbol: inflateReset
```

**Comment by sangshuduo** [comment]
这个问题最近在看，但在全新安装的 CentOS 7.9，包括使用 docker 安装和 VirtualBox 安装的环境，都无法重现。怀疑是环境问题。
能否试一下 docker run -dit centos:centos7 然后在里面装一下 TDengine 和 taosTools 看还有没有同样问题？

**Comment by czzt1** [comment]
遇到了同样的问题，环境为Ubuntu 22.04.1 LTS

**Comment by czzt1** [comment]
> 遇到了同样的问题，环境为Ubuntu 22.04.1 LTS

补充一下，taosd版本3.0.1.0,taostool版本2.1.3

**Comment by czzt1** [comment]
> > 遇到了同样的问题，环境为Ubuntu 22.04.1 LTS
> 
> 麻烦安装一个全新的 Ubuntu 22.04 环境试一下

使用ubuntu:22.04 docker镜像，可以复现
`➜  ~ docker cp  taosTools-2.1.3-Linux-x64.deb ubuntu:/root/
➜  ~ docker exec -it ubuntu bash
root@4e0177423a4f:/# ls
TDengine-server-3.0.1.0-Linux-x64.deb  boot  etc   lib    lib64   media  opt   root  sbin  sys  usr
bin                                    dev   home  lib32  libx32  mnt    proc  run   srv   tmp  var
root@4e0177423a4f:/# cd ~
root@4e0177423a4f:~# ls
taosTools-2.1.3-Linux-x64.deb
root@4e0177423a4f:~# dpkg -i taosTools-2.1.3-Linux-x64.deb
Selecting previously unselected package taostools.
(Reading database ... 5578 files and directories currently installed.)
Preparing to unpack taosTools-2.1.3-Linux-x64.deb ...
Unpacking taostools (2.1.3) ...
Setting up taostools (2.1.3) ...
root@4e0177423a4f:~# taosdump
taosdump: symbol lookup error: taosdump: undefined symbol: inflateReset
root@4e0177423a4f:~#`

**Comment by czzt1** [comment]
`➜  ~ docker cp  taosTools-2.1.3-Linux-x64.deb ubuntu:/root/`
`➜  ~ docker exec -it ubuntu bash`
`root@4e0177423a4f:/# ls`
`TDengine-server-3.0.1.0-Linux-x64.deb  boot  etc   lib    lib64   media  opt   root  sbin  sys  usr`
`bin                                    dev   home  lib32  libx32  mnt    proc  run   srv   tmp  var`
`root@4e0177423a4f:/# cd ~`
`root@4e0177423a4f:~# ls`
`taosTools-2.1.3-Linux-x64.deb`
`root@4e0177423a4f:~# dpkg -i taosTools-2.1.3-Linux-x64.deb`
`Selecting previously unselected package taostools.`
`(Reading database ... 5578 files and directories currently installed.)`
`Preparing to unpack taosTools-2.1.3-Linux-x64.deb ...`
`Unpacking taostools (2.1.3) ...`
`Setting up taostools (2.1.3) ...`
`root@4e0177423a4f:~# taosdump`
`taosdump: symbol lookup error: taosdump: undefined symbol: inflateReset`
`root@4e0177423a4f:~#`

**Comment by sangshuduo** [comment]
![image](https://user-images.githubusercontent.com/825729/189042955-38e83c58-2fe2-484a-81c8-09e18307954b.png)

**Comment by sangshuduo** [comment]
![image](https://user-images.githubusercontent.com/825729/189043650-7253dde1-00e7-430b-85e6-5043e3a62dce.png)

**Comment by redgreat** [comment]
> ![image](https://user-images.githubusercontent.com/825729/189043650-7253dde1-00e7-430b-85e6-5043e3a62dce.png)

官方下载的包名跟你这个不一样，但是版本号却一样

我下载源码编译安装，需要翻墙git clone的太多了，连接直接挂了，麻烦给个 安装包吧

**Comment by sangshuduo** [comment]
名字不一样只是我自己为了区分加的，实际上我是特意从官网下载安装测试的

**Comment by czzt1** [comment]
使用官网下载的deb包后问题解决，是否github release的deb有问题？

**Comment by sangshuduo** [comment]
> 使用官网下载的deb包后问题解决，是否github release的deb有问题？

有一种可能性是下载的文件不完整，如果电脑上还保留之前无法安装的包，麻烦 md5sum 一下看看值是多少

**Comment by czzt1** [comment]
> > 使用官网下载的deb包后问题解决，是否github release的deb有问题？
> 
> 有一种可能性是下载的文件不完整，如果电脑上还保留之前无法安装的包，麻烦 md5sum 一下看看值是多少

找到问题了，第一次下载taosTools我使用了wget，经过测试wget下载的deb包和使用浏览器下载的包md5不一致

**Comment by hellpup** [comment]
在官网下载的taosTools-2.2.1,在同一台机上TDengine 2.6.0.10时候运行正常，后升级到3.0.1.2后，同样的文件执行提示
taosdump: symbol lookup error: taosdump: undefined symbol: inflateReset
可以判断，不是上面提到的下载问题

**Comment by hellpup** [comment]
> > 在官网下载的taosTools-2.2.1,在同一台机上TDengine 2.6.0.10时候运行正常，后升级到3.0.1.2后，同样的文件执行提示 taosdump: symbol lookup error: taosdump: undefined symbol: inflateReset 可以判断，不是上面提到的下载问题
> 
> 步骤就是安装 TDengine 2.6.0.10 ，然后 taosTools 2.2.1，然后 TDengine 3.0.1.2，这样吗？麻烦告知一下 Linux host 是哪个 distro 的什么版本？安装 TDengine 和 taos-tools 的安装包格式是什么？我重现一下
步骤之前安装的 TDengine 2.6.0.10 ，taosTools 2.2.1，然后 TDengine 3.0.1.2
linux host： Debian 11.5
安装TDengine使用 deb [arch=amd64] http://repos.taosdata.com/tdengine-stable stable main
apt install tdengine
taoTools使用官网的deb包
wget https://www.taosdata.com/assets-download/taosTools-2.1.3-Linux-x64.deb
dpkg -i taosTools-2.1.3-Linux-x64.deb

**Comment by zeje** [comment]
宿主主机centos8
root@fc29839c0272:~# taosdump -V
taosdump: symbol lookup error: taosdump: undefined symbol: inflateReset

如下一样结果：

docker-compose启动centos7镜像
version: '3'
services:
  centos_taosdump:
    restart: always
    image: centos:centos7
    container_name: centos_taosdump
    stdin_open: true
    tty: true
    privileged: true
    ports:
      - "8022:22"
yum install -y wget
wget https://www.taosdata.com/assets-download/3.0/TDengine-server-3.0.2.0-Linux-x64.rpm
rpm -iv TDengine-server-3.0.2.0-Linux-x64.rpm
wget https://www.taosdata.com/assets-download/taosTools-2.3.1-Linux-x64.rpm
rpm -iv taosTools-2.3.1-Linux-x64.rpm 

docker-compose启动ubuntu:22.04镜像
version: '3'
services:
  ubuntu_taosdump:
    restart: always
    image: ubuntu:22.04
    container_name: centos_taosdump
    stdin_open: true
    tty: true
    privileged: true
    ports:
      - "8022:22"
cd ~
apt-get update
apt-get install -y wget
wget https://www.taosdata.com/assets-download/3.0/TDengine-server-3.0.2.0-Linux-x64.deb
dpkg -i TDengine-server-3.0.2.0-Linux-x64.deb
wget https://www.taosdata.com/assets-download/taosTools-2.3.1-Linux-x64.deb
dpkg -i taosTools-2.3.1-Linux-x64.deb

**Comment by sangshuduo** [comment]
> 宿主主机centos8 root@fc29839c0272:~# taosdump -V taosdump: symbol lookup error: taosdump: undefined symbol: inflateReset
> 
> 如下一样结果：
> 
> docker-compose启动centos7镜像 version: '3' services: centos_taosdump: restart: always image: centos:centos7 container_name: centos_taosdump stdin_open: true tty: true privileged: true ports: - "8022:22" yum install -y wget wget https://www.taosdata.com/assets-download/3.0/TDengine-server-3.0.2.0-Linux-x64.rpm rpm -iv TDengine-server-3.0.2.0-Linux-x64.rpm wget https://www.taosdata.com/assets-download/taosTools-2.3.1-Linux-x64.rpm rpm -iv taosTools-2.3.1-Linux-x64.rpm
> 
> docker-compose启动ubuntu:22.04镜像 version: '3' services: ubuntu_taosdump: restart: always image: ubuntu:22.04 container_name: centos_taosdump stdin_open: true tty: true privileged: true ports: - "8022:22" cd ~ apt-get update apt-get install -y wget wget https://www.taosdata.com/assets-download/3.0/TDengine-server-3.0.2.0-Linux-x64.deb dpkg -i TDengine-server-3.0.2.0-Linux-x64.deb wget https://www.taosdata.com/assets-download/taosTools-2.3.1-Linux-x64.deb dpkg -i taosTools-2.3.1-Linux-x64.deb
> 
> 使用3.0的，下载链接需要修正，修正后使用正常 wget https://www.taosdata.com/assets-download/3.0/taosTools-2.3.2-Linux-x64.rpm rpm -iv taosTools-2.3.2-Linux-x64.rpm
> 
> wget https://www.taosdata.com/assets-download/3.0/taosTools-2.3.2-Linux-x64.deb dpkg -i taosTools-2.3.2-Linux-x64.deb
> 
> 链接问题： v3.0 》参考手册》taosdump》所有下载链接 下到的是2.x的 v3.0 》taosTools 发布历史及下载链接，下到的是3.x的

已修改，谢谢指出
