### ISSUE TITLE
ERROR: Failed to open file  /home/taosdb/backups001/dbs.sql

### ISSUE THREAD

**Issue by hshzhxlk** [taosdata/taos-tools#383]
Backup is normal！

**Comment by hshzhxlk** [comment]
The backup is normal, and the data cannot be recovered！

**Comment by sangshuduo** [comment]
Please let me know what taosdump version you use and what TDengine version you use. Please attach dump_result.txt and dbs.sql file too. Thanks.

**Comment by hshzhxlk** [comment]
==============================
========== arguments config =========
taosdump version 2.2.2
host: localhost
user: root
port: 6030
outpath: 
inpath:  /home/taosdb-3/backups001
resultFile: ./dump_result.txt
all_databases: false
databases: false
databasesSeq: (null)
schemaonly: false
with_property: true
answer_yes: false
avro codec: snappy
data_batch: 16383
thread_num: 8
allow_sys: false
escape_char: true
loose_mode: false
isDumpIn: true
arg_list_len: 0
INFO: dumpInWithDbPath(), dump in from  /home/taosdb-3/backups001 ...
ERROR: Failed to open file  /home/taosdb-3/backups001/dbs.sql
ERROR: Failed to dump database(s) in!

**Comment by hshzhxlk** [comment]
Docker compose installation tdengine3.0.1.2

**Comment by hshzhxlk** [comment]
ERROR: Failed to open file  /home/taosdb-3/backups001/dbs.sql

**Comment by hshzhxlk** [comment]
[root@VM-4-9-centos backups001]# cat dbs.sql 
#!server_ver: ver:3.0.1.2
#!taosdump_ver: 2.2.2_318246c
#!escape_char: true
#!loose_mode: false
#!charset: UTF-8
#!dumpdb: test:

**Comment by hshzhxlk** [comment]
========== arguments config =========
taosdump version 2.2.2, commit: 318246c
host: (null)
user: root
port: 0
outpath: /home/taosdb-3/backups001/
inpath: 
resultFile: ./dump_result.txt
all_databases: false
databases: true
databasesSeq: test
schemaonly: false
with_property: true
answer_yes: false
avro codec: snappy
data_batch: 50
thread_num: 4
allow_sys: false
escape_char: true
loose_mode: false
isDumpIn: false
arg_list_len: 0
debug_print: 0
========== DUMP OUT ========== 
# DumpOut start time: 2022-09-23 02:42:05

#### database:                       test

============================== TOTAL STATISTICS ============================== 
# total database count:     1
# total super table count:  0
# total child table count:  0
# total row count:          8

========== arguments config =========
taosdump version 2.2.2, commit: 318246c
host: (null)
user: root
port: 0
outpath: 
inpath:  /home/taosdb-3/backups001
resultFile: ./dump_result.txt
all_databases: false
databases: false
databasesSeq: (null)
schemaonly: false
with_property: true
answer_yes: false
avro codec: snappy
data_batch: 16383
thread_num: 8
allow_sys: false
escape_char: true
loose_mode: false
isDumpIn: true
arg_list_len: 0
debug_print: 0
========== DUMP IN ========== 
# DumpIn start time: 2022-09-23 02:43:34
========== arguments config =========
taosdump version 2.2.2, commit: 318246c
host: localhost
user: root
port: 6030
outpath: 
inpath:  /home/taosdb-3/backups001
resultFile: ./dump_result.txt
all_databases: false
databases: false
databasesSeq: (null)
schemaonly: false
with_property: true
answer_yes: false
avro codec: snappy
data_batch: 16383
thread_num: 8
allow_sys: false
escape_char: true
loose_mode: false
isDumpIn: true
arg_list_len: 0
debug_print: 0
========== DUMP IN ========== 
# DumpIn start time: 2022-09-23 03:32:39
========== arguments config =========
taosdump version 2.2.2, commit: 318246c
host: localhost
user: root
port: 6030
outpath: 
inpath:  /home/taosdb-3/backups001
resultFile: ./dump_result.txt
all_databases: false
databases: false
databasesSeq: (null)
schemaonly: false
with_property: true
answer_yes: false
avro codec: snappy
data_batch: 16383
thread_num: 8
allow_sys: false
escape_char: true
loose_mode: false
isDumpIn: true
arg_list_len: 0
debug_print: 0
========== DUMP IN ========== 
# DumpIn start time: 2022-09-23 03:36:46
========== arguments config =========
taosdump version 2.2.2, commit: 318246c
host: localhost
user: root
port: 6030
outpath: 
inpath:  /home/taosdb-3/backups001
resultFile: ./dump_result.txt
all_databases: false
databases: false
databasesSeq: (null)
schemaonly: false
with_property: true
answer_yes: false
avro codec: snappy
data_batch: 16383
thread_num: 8
allow_sys: false
escape_char: true
loose_mode: false
isDumpIn: true
arg_list_len: 0
debug_print: 0
========== DUMP IN ========== 
# DumpIn start time: 2022-09-23 03:37:51

**Comment by sangshuduo** [comment]
Please check the permission of dbs.sql with ls -l. 
I can't reproduce it on my side. Both dump out and dump in are okay.

**Comment by hshzhxlk** [comment]
[root@VM-4-9-centos backups001]# ls -l
total 8
-rwxr-xrw- 1 root root  131 Sep 23 10:42 dbs.sql
drwxrwxr-x 3 root root 4096 Sep 23 10:42 taosdump.3327801851464

**Comment by hshzhxlk** [comment]
-rw-rw-rw- 1 root root  131 Sep 23 02:42 dbs.sql
-rw-r--r-- 1 root root 1581 Sep 23 05:26 dump_result.txt
drwxrwxr-x 3 root root 4096 Sep 23 02:42 taosdump.3327801851464

**Comment by hshzhxlk** [comment]
root@tdengine_host:/usr/local/taos/bin# cd /home/taosdb-3/backups001
root@tdengine_host:/home/taosdb-3/backups001# ls -l
total 12
-rw-rw-rw- 1 root root  131 Sep 23 02:42 dbs.sql
-rw-r--r-- 1 root root 1581 Sep 23 05:26 dump_result.txt
drwxrwxr-x 3 root root 4096 Sep 23 02:42 taosdump.3327801851464

**Comment by hshzhxlk** [comment]
root@tdengine_host:/usr/local/taos/bin# cd /home/taosdb-3/backups001
root@tdengine_host:/home/taosdb-3/backups001# ls -l
total 12
-rw-rw-rw- 1 root root  131 Sep 23 02:42 dbs.sql
-rw-r--r-- 1 root root 1581 Sep 23 05:26 dump_result.txt
drwxrwxr-x 3 root root 4096 Sep 23 02:42 taosdump.3327801851464
root@tdengine_host:/home/taosdb-3/backups001# cd /usr/local/taos/bin/
root@tdengine_host:/usr/local/taos/bin# 
root@tdengine_host:/usr/local/taos/bin# 
root@tdengine_host:/usr/local/taos/bin# taosdump -i /home/taosdb-3/backups001
bash: taosdump -i /home/taosdb-3/backups001: No such file or directory
root@tdengine_host:/usr/local/taos/bin# 
root@tdengine_host:/usr/local/taos/bin#

**Comment by hshzhxlk** [comment]
root@tdengine_host:/home/taosdb-3/backups001# ls -l
total 12
-rw-rw-rw- 1 root root  131 Sep 23 02:42 dbs.sql
-rw-r--r-- 1 root root 1581 Sep 23 05:26 dump_result.txt
drwxrwxr-x 3 root root 4096 Sep 23 02:42 taosdump.3327801851464
root@tdengine_host:/home/taosdb-3/backups001# cd /usr/local/taos/bin/
root@tdengine_host:/usr/local/taos/bin# 
root@tdengine_host:/usr/local/taos/bin# 
root@tdengine_host:/usr/local/taos/bin# taosdump -i /home/taosdb-3/backups001
bash: taosdump -i /home/taosdb-3/backups001: No such file or directory
root@tdengine_host:/usr/local/taos/bin# 
root@tdengine_host:/usr/local/taos/bin# taosdump -h localhost -P 6030  -u root -ptaosdata -c /etc/taos/taos.cfg -i /home/taosdb-3/backups001
==============================
========== arguments config =========
taosdump version 2.2.2
host: localhost
user: root
port: 6030
outpath: 
inpath:  /home/taosdb-3/backups001
resultFile: ./dump_result.txt
all_databases: false
databases: false
databasesSeq: (null)
schemaonly: false
with_property: true
answer_yes: false
avro codec: snappy
data_batch: 16383
thread_num: 8
allow_sys: false
escape_char: true
loose_mode: false
isDumpIn: true
arg_list_len: 0
INFO: dumpInWithDbPath(), dump in from  /home/taosdb-3/backups001 ...
ERROR: Failed to open file  /home/taosdb-3/backups001/dbs.sql
ERROR: Failed to dump database(s) in!
root@tdengine_host:/usr/local/taos/bin#

**Comment by hshzhxlk** [comment]
root@tdengine_host:/usr/local/taos/bin# taosdump -i /home/taosdb-3/backups001
bash: taosdump -i /home/taosdb-3/backups001: No such file or directory
root@tdengine_host:/usr/local/taos/bin# 
root@tdengine_host:/usr/local/taos/bin# taosdump -h localhost -P 6030  -u root -ptaosdata -c /etc/taos/taos.cfg -i /home/taosdb-3/backups001
==============================
========== arguments config =========
taosdump version 2.2.2
host: localhost
user: root
port: 6030
outpath: 
inpath:  /home/taosdb-3/backups001
resultFile: ./dump_result.txt
all_databases: false
databases: false
databasesSeq: (null)
schemaonly: false
with_property: true
answer_yes: false
avro codec: snappy
data_batch: 16383
thread_num: 8
allow_sys: false
escape_char: true
loose_mode: false
isDumpIn: true
arg_list_len: 0
INFO: dumpInWithDbPath(), dump in from  /home/taosdb-3/backups001 ...
ERROR: Failed to open file  /home/taosdb-3/backups001/dbs.sql
ERROR: Failed to dump database(s) in!
root@tdengine_host:/usr/local/taos/bin#

**Comment by sangshuduo** [comment]
"No such file or directory" looks like an environmental issue. Taosdump doesn't output such information. I can't reproduce on my side whatever host, docker, and host-to-docker. Please switch to another kind of environment and try again.

**Comment by hshzhxlk** [comment]
It is operated in the container.
Not on the host

**Comment by hshzhxlk** [comment]
taosdump -i /home/taosdb-3/backups001

**Comment by hshzhxlk** [comment]
root@tdengine_host:/usr/local/taos/bin# taosdump -i /home/taosdb-3/backups001
bash: taosdump -i /home/taosdb-3/backups001: No such file or directory
root@tdengine_host:/usr/local/taos/bin#

**Comment by hshzhxlk** [comment]
root@tdengine_host:/usr/local/taos/bin# taosdump -h localhost -P 6030  -u root -ptaosdata -c /etc/taos/taos.cfg -i /home/taosdb-3/backups001
==============================
========== arguments config =========
taosdump version 2.2.2
host: localhost
user: root
port: 6030
outpath: 
inpath:  /home/taosdb-3/backups001
resultFile: ./dump_result.txt
all_databases: false
databases: false
databasesSeq: (null)
schemaonly: false
with_property: true
answer_yes: false
avro codec: snappy
data_batch: 16383
thread_num: 8
allow_sys: false
escape_char: true
loose_mode: false
isDumpIn: true
arg_list_len: 0
INFO: dumpInWithDbPath(), dump in from  /home/taosdb-3/backups001 ...
ERROR: Failed to open file  /home/taosdb-3/backups001/dbs.sql
ERROR: Failed to dump database(s) in!
root@tdengine_host:/usr/local/taos/bin#

**Comment by hshzhxlk** [comment]
taosdump -h localhost -P 6030  -u root -ptaosdata -c /etc/taos/taos.cfg -i /home/taosdb-3/backups001

**Comment by hshzhxlk** [comment]
taosdump -i /home/taosdb-3/backups001
taosdump -h localhost -P 6030 -u root -ptaosdata -c /etc/taos/taos.cfg -i /home/taosdb-3/backups001
The error prompts are different

**Comment by sangshuduo** [comment]
I have no idea. However taosdump does not output No such file or directory. :)

**Comment by hshzhxlk** [comment]
Prompt invalid command when the command has illegal characters

**Comment by hshzhxlk** [comment]
There is no such file or directory, which has misled me v^v.
The command just now has illegal characters.

**Comment by hshzhxlk** [comment]
Thank you very much. Have a nice weekend.
