### ISSUE TITLE
Data backup is an sql file

### ISSUE THREAD

**Issue by hshzhxlk** [taosdata/taos-tools#388]

**Comment by hshzhxlk** [comment]
DML

**Comment by sangshuduo** [comment]
?

**Comment by hshzhxlk** [comment]
When backing up a dml statement, it is not an sql file

**Comment by hshzhxlk** [comment]
Need to add special parameters

**Comment by sangshuduo** [comment]
TDengine does not support to record them. So taosdump has no way to backup them too.

**Comment by sangshuduo** [comment]
close as not taos-tools related.
