### ISSUE TITLE
ERROR: writeResultToAvroNative() LN5048, actual dump out: 5280, batch 126668

### ISSUE THREAD

**Issue by hshzhxlk** [taosdata/taos-tools#389]

**Comment by sangshuduo** [comment]
Please list what version TDengine you use, what version taosdump you use, what data  schema is, how many DBs, how many super tables, how many tables, how many records, what command line you use, and upload dump_result.txt

**Comment by hshzhxlk** [comment]
TDengine 3.0.1.2
taosdump version 2.2.2, commit: 318246c
host: (null)
user: root
port: 0
outpath: /home/taosdb-3/backups003/
inpath: 
resultFile: ./dump_result.txt
all_databases: false
databases: true
databasesSeq: mdap_wjw_v3_dev
schemaonly: false
with_property: true
answer_yes: false
avro codec: snappy
data_batch: 16383
thread_num: 8
allow_sys: false
escape_char: true
loose_mode: false
isDumpIn: false
arg_list_len: 0
debug_print: 0

**Comment by sangshuduo** [comment]
please use same command line plus '-g' and capture output to a file like
```
taosdump -D mdap_wjw_v3_dev -g | tee out.txt
```
and upload out.txt

**Comment by hshzhxlk** [comment]
[out.txt](https://github.com/taosdata/taos-tools/files/9652917/out.txt)

**Comment by sangshuduo** [comment]
> [out.txt](https://github.com/taosdata/taos-tools/files/9652917/out.txt)

According to the output, the dump is succeed without any error.

**Comment by sangshuduo** [comment]
close as no update
