### ISSUE TITLE
taosdump导出文件报错

### ISSUE THREAD

**Issue by jamesZHANG500** [taosdata/taos-tools#398]
报错信息
zkj@:2022-10-10$ taosdump -A -L
==============================
========== arguments config =========
taosdump version 2.2.4
host: (null)
user: root
port: 0
outpath: 
inpath: 
resultFile: ./dump_result.txt
all_databases: true
databases: false
databasesSeq: (null)
schemaonly: false
with_property: true
answer_yes: false
avro codec: snappy
data_batch: 16383
thread_num: 8
allow_sys: false
escape_char: true
loose_mode: true
isDumpIn: false
arg_list_len: 0
OK: Database: db_26 exists
OK: Database: db_18 exists
OK: Database: db_49 exists
OK: Database: db_50 exists
OK: Database: db_12 exists
OK: Database: db_44 exists
OK: Database: db_48 exists
OK: Database: db_45 exists
OK: Database: db_14 exists
OK: Database: db_41 exists
OK: Database: db_13 exists
OK: Database: db_1 exists
OK: Database: db_47 exists
OK: Database: db_25 exists
OK: Database: db_43 exists
OK: Database: db_2 exists
OK: Database: db_11 exists
OK: Database: db_21 exists
OK: Database: db_40 exists
OK: Database: db_15 exists
OK: Database: db_9 exists
OK: Database: db_46 exists
OK: Database: db_17 exists
OK: Database: db_42 exists
OK: Database: db_27 exists
INFO: Start to dump out database: db_26
INFO: Getting tables' number of super table (logrecord) ...
INFO: dumpNtbOfStbByThreads() LN10417, db_26's logrecord's total normal table count: 0
INFO: Getting tables' number of super table (properties_p3p0do07q12) ...
INFO: dumpNtbOfStbByThreads() LN10417, db_26's properties_p3p0do07q12's total normal table count: 0
WARN: dumpNTablesOfDbNative() LN10846, database: db_26 has 0 tables
OK: Database db_26 dumped
INFO: Start to dump out database: db_18
INFO: Getting tables' number of super table (scenehistory) ...
INFO: dumpNtbOfStbByThreads() LN10417, db_18's scenehistory's total normal table count: 0
INFO: Getting tables' number of super table (device_log_p98p4sjny19) ...
INFO: dumpNtbOfStbByThreads() LN10417, db_18's device_log_p98p4sjny19's total normal table count: 0
INFO: Getting tables' number of super table (smsrecord) ...
INFO: dumpNtbOfStbByThreads() LN10417, db_18's smsrecord's total normal table count: 0
INFO: Getting tables' number of super table (statecount) ...
INFO: dumpNtbOfStbByThreads() LN10417, db_18's statecount's total normal table count: 1
INFO: connection: 0x5591a2ba1a80 is dumping out schema of sub-table(s) of statecount 
INFO: Getting tables' number of super table (statecount) ...
INFO: The number of tables of statecount is 1!
INFO: connection 0x5591a2ba1a80 fetched 100% of statecount' tbname
OK: total 1 sub-table's name of stable: statecount fetched
INFO: The number of tables of statecount be filled is 1!
INFO: connection 0x5591a2ba1a80 is dumping out schema:0% of statecount
ERROR: getTableTagValueNativeV2() LN2780, failed to run command <SELECT typeFROM db_18.statecount_dfcc3114eba075be491b45ed4932f800 LIMIT 1>, taos: 0x5591a2ba1a80, code: 0x80000216, reason: syntax error near ".statecount_dfcc3114eba075be491b45ed4932f800
INFO: connection 0x5591a2ba1a80 is dumping out schema:100% of statecount
OK: total 1 sub table(s) of stable: statecount dumped
ERROR: Invalid time precision: .
ERROR: dumpNtbOfStbByThreads() LN10548, get precision error
超级表结构
![image](https://user-images.githubusercontent.com/7957917/194804429-bd46a959-e9dd-4d6c-bc83-0dd2d5c3b1a1.png)

taosdump -V
taosdump version 2.2.4

数据库版本 ：
Welcome to the TDengine shell from Linux, Client Version:2.2.2.10
Copyright (c) 2020 by TAOS Data, Inc. All rights reserved.

**Comment by sangshuduo** [comment]
已修复，将在下一次发版中包含
