### ISSUE TITLE
unreadable code

### ISSUE THREAD

**Issue by zeje** [taosdata/taos-tools#405]
驱动版本：taos-jdbcdriver-3.0.1-dist
使用dbweaver22.0.0时，使用restful驱动时，元数据显示异常，表名等都是十六进制的字符

jdbc方式，元数据正常
![image](https://user-images.githubusercontent.com/10680634/195755906-6be84867-d69c-4184-a10f-c09af0765177.png)
再次使用restful驱动查看时，元数据显示正常

**Comment by sangshuduo** [comment]
Please submit issue to the repo https://github.com/taosdata/taos-connector-jdbc.
