### ISSUE TITLE
3.0.1.8 version windows open taosdump.exe failed

### ISSUE THREAD

**Issue by zhangkanglei** [taosdata/taos-tools#491]
![a360aed7117b2a3679e0b13b0c13294](https://user-images.githubusercontent.com/27048667/204179235-27760ff0-72b8-4ebd-a519-a40e96bc8f73.png)

**Comment by sangshuduo** [comment]
[zlib.zip](https://github.com/taosdata/taos-tools/files/10100136/zlib.zip)
请下载附件文件，解压缩到 C:\TDengine 目录下看是否能解决问题。下个版本我们会正式修复

**Comment by zhangkanglei** [comment]
![image](https://user-images.githubusercontent.com/27048667/204184615-1354da7c-43e8-4263-9976-ef584567e0e2.png)
又换了个报错

**Comment by zhangkanglei** [comment]
> [zlib.zip](https://github.com/taosdata/taos-tools/files/10100136/zlib.zip) 请下载附件文件，解压缩到 C:\TDengine 目录下看是否能解决问题。下个版本我们会正式修复

看能一次性把所需要的文件都发一下不

**Comment by sangshuduo** [comment]
太大，无法发完整的。可以自己使用 Visual Studio 编译。建议安装 Visual Studio 2022, git for windows, cmake for windows。步骤如下

git clone https://github.com/taosdata/TDengine
mkdir debug
cd debug
cmake .. -G "NMake Makefiles"
nmake

**Comment by sangshuduo** [comment]
另外请问在 Windows 下使用 taosBenchmark 也有同样的问题吗？

**Comment by sangshuduo** [comment]
> ![image](https://user-images.githubusercontent.com/27048667/204184615-1354da7c-43e8-4263-9976-ef584567e0e2.png) 又换了个报错

https://www.microsoft.com/en-US/download/details.aspx?id=48145

**Comment by zhangkanglei** [comment]
> 另外请问在 Windows 下使用 taosBenchmark 也有同样的问题吗？

taosBenchmark 没有问题

**Comment by sangshuduo** [comment]
> > 另外请问在 Windows 下使用 taosBenchmark 也有同样的问题吗？
> 
> taosBenchmark 没有问题

好的，谢谢
