### ISSUE TITLE
taosdump 2.3.2 Restore incomplete

### ISSUE THREAD

**Issue by zeje** [taosdata/taos-tools#516]
同一个交换机下的网络，服务端在linux宿主机（centos8），备份到了windows（win 11)，

服务端版本：3.0.2.0
客户端版本：TDengine-client-3.0.2.0-Windows-x64.exe
taosdump version 2.3.2

性能问题：
30多亿条数据，备份了18个小时（可以通过添加线程数，缩短时间）

还原问题：
不到1分钟，完成了，实际上是中断了
![329ebbdff8a8e12d2cfb3581c3fe775](https://user-images.githubusercontent.com/10680634/207240365-2ebf43d4-53be-4038-b034-6efa5a985b41.png)

-- 数据库 1个
-- 超级表
select count(*) from information_schema.ins_stables; --113 还原后113
select count(*) from information_schema.ins_tables; --120030 还原后120030
-- 有数据的超级表
select count(*) from loctube.event_tdstore_gps; -- 555972745 3.75s  还原后1527167,重新尝试1530934
select count(*) from loctube.event_tdstore_isactitem; --1158279812 1.85s  还原后773084,重新尝试769818
select count(*) from loctube.event_tdstore_status; -- 555972746 35.833s 3.323s 3.308s 还原后0,重新尝试0
select count(*) from loctube.event_tdstore_generallocation; --555958629 1.974s 811ms 还原后1525260,重新尝试1527709
select count(*) from loctube.device_log_tdstore; -- 579594237 1.57s 还原后1420280,重新尝试1417324

**Comment by zeje** [comment]
查看客户端日志，最后部分如下：
12/13 09:31:35.435000 00025708 QRY WARN Acquire sch job failed, may be dropped, jobId:0x0
12/13 09:31:35.435000 00025708 QRY WARN Acquire sch job failed, may be dropped, jobId:0x51d5b0
12/13 09:31:35.436000 00025708 QRY WARN Acquire sch job failed, may be dropped, jobId:0x0
12/13 09:31:36.937000 00025708 QRY WARN Acquire sch job failed, may be dropped, jobId:0x0
12/13 09:31:38.440000 00025708 QRY WARN Acquire sch job failed, may be dropped, jobId:0x522e07
12/13 09:31:38.440000 00025708 QRY WARN Acquire sch job failed, may be dropped, jobId:0x0
12/13 09:31:38.441000 00025708 QRY WARN Acquire sch job failed, may be dropped, jobId:0x0
12/13 09:31:39.942000 00025708 QRY WARN Acquire sch job failed, may be dropped, jobId:0x0
12/13 09:31:39.942000 00025708 QRY WARN Acquire sch job failed, may be dropped, jobId:0x0
12/13 09:31:39.943000 00025708 QRY WARN Acquire sch job failed, may be dropped, jobId:0x0
12/13 09:31:41.445000 00025708 QRY WARN Acquire sch job failed, may be dropped, jobId:0x528429
12/13 09:31:41.445000 00025708 QRY WARN Acquire sch job failed, may be dropped, jobId:0x52842a
12/13 09:31:41.445000 00025708 QRY WARN Acquire sch job failed, may be dropped, jobId:0x0
12/13 09:31:42.951000 00026136 QRY ERROR CTG:00000277973A5B20 invalid db vgInfo, dbFName:information_schema, vgHash:00000277EB9247E0, vgVersion:40, vgHashSize:0
12/13 09:31:44.451000 00025708 QRY WARN Acquire sch job failed, may be dropped, jobId:0x0
12/13 09:31:47.455000 00025708 QRY WARN Acquire sch job failed, may be dropped, jobId:0x533000
12/13 09:31:47.456000 00025708 QRY WARN Acquire sch job failed, may be dropped, jobId:0x0
12/13 09:31:47.456000 00025708 QRY WARN Acquire sch job failed, may be dropped, jobId:0x0
12/13 09:31:47.457000 00025708 QRY WARN Acquire sch job failed, may be dropped, jobId:0x0
12/13 09:31:48.958000 00025708 QRY WARN Acquire sch job failed, may be dropped, jobId:0x0
12/13 09:31:48.959000 00025708 QRY WARN Acquire sch job failed, may be dropped, jobId:0x0
12/13 09:31:51.967000 00026136 QRY ERROR CTG:00000277973A5B20 invalid db vgInfo, dbFName:information_schema, vgHash:00000277BC2A71A0, vgVersion:40, vgHashSize:0
12/13 09:31:51.963000 00025708 QRY WARN Acquire sch job failed, may be dropped, jobId:0x0
12/13 09:31:51.964000 00025708 QRY WARN Acquire sch job failed, may be dropped, jobId:0x0
12/13 09:31:53.467000 00025708 QRY WARN Acquire sch job failed, may be dropped, jobId:0x0

**Comment by sangshuduo** [comment]
Windows 版验证不够重复，请先用 Linux 版

**Comment by zeje** [comment]
window上taosdump备份的文件，使用linux上的taosdump还原，出现大量的error跟warn。

ERROR: getTableDesNative() LN2858, failed to run command <DESCRIBE (null).`event_tdstore_systemtime`>, taos: 0x7fbf58004670, code: 0x80002600, reason: syntax error near "(null).`event_tdstore_systemtime`"
ERROR: dumpInAvroTbTagsImpl() LN5906 Unknown type: 8
ERROR: dumpInAvroTbTagsImpl() LN5906 Unknown type: 8
ERROR: getTableDesNative() LN2858, failed to run command <DESCRIBE (null).`event_tdstore_gps`>, taos: 0x7fbf54004670, code: 0x80002600, reason: syntax error near "(null).`event_tdstore_gps`"
ERROR: dumpInAvroTbTagsImpl() LN5906 Unknown type: 8
ERROR: dumpInAvroTbTagsImpl() LN5906 Unknown type: 8

**Comment by sangshuduo** [comment]
代码中已修复，包含在下一个版本中
