### ISSUE TITLE
taosdump 数据增量备份问题

### ISSUE THREAD

**Issue by horseinblack** [taosdata/taos-tools#536]
环境: 
   系统:CentOS7
   taos版本: 2.4.0.30

问题描述:
   我想使用taosdump进行数据备份, 每天备份一次,每次只备份前一天的数据, 使用工具的命令如下:
  taosdump -uroot \
    -pxxxxx -hlocalhost  \
    -o /taosbackup/2022/12/28  \
    --start-time --databases=xxx \
    --start-time='2022-12-28T00:00:00.000+0800'  \
    --end-time='2022-12-29T00:00:00.000+0800' 
  使用该命令后导出来的数据有20多个G
但是我们的每天的增量也没有那么多,导出成csv文件的话也就i几百兆,最多1G
感觉--start-time  --end-time 没有起到作用
这是导数据的过程中的一个截图
![e04cd70b1d5e6d16a93982cc6812bae](https://user-images.githubusercontent.com/63383684/210058751-4321a6ff-4b39-4de3-ae2d-1343aac39730.png)
请问这是什么原因呢?是我哪个参数格式不正确么?

**Comment by sangshuduo** [comment]
taosdump 什么版本？

**Comment by horseinblack** [comment]
> taosdump 什么版本？
安装taosd ( 2.4.0.30 ) 时自带的
taosdump version 1.4.6-2-ga875a05_a875a05

**Comment by sangshuduo** [comment]
> > taosdump 什么版本？
> > 安装taosd ( 2.4.0.30 ) 时自带的
> > taosdump version 1.4.6-2-ga875a05_a875a05

请使用这个链接中的最新版本
https://www.taosdata.com/all-downloads#taos_tools_tar-list
