### ISSUE TITLE
taosdump导入数据非常慢

### ISSUE THREAD

**Issue by yupingsong-anylink-io** [taosdata/taos-tools#649]
tdengine版本：2.6.0.6
服务器：2核8G

1个超级表，子表6w

使用taosdump导出数据，然后再使用taosdump导入数据。
数据量大概在12G左右
导入数据用了将近30个小时

**Comment by sangshuduo** [comment]
超级表和子表的数量是多少？核数有点太少了

**Comment by yupingsong-anylink-io** [comment]
> 

1个超级表，子表6w左右

**Comment by sangshuduo** [comment]
> 1个超级表，子表6w左右 会有一些子表没数据，总的数据量是12G

子表 schema 多少列？

**Comment by yupingsong-anylink-io** [comment]
子表4列：
`htime` timestamp
`value` double,
`quality` int,
`source` int

TAGS 有两列
`deviceid` int
`itemid` int

**Comment by sangshuduo** [comment]
![](https://user-images.githubusercontent.com/825729/233520100-f16e3fed-281b-4b41-8969-74a488d804fb.png)

搭了一个 2c8G 的虚拟机。用 taosBenchmark 模拟相同schema 的数据，65000 个表，每个表 15000 记录，占磁盘空间 15G，备份导出花了 23分钟，导入花了 440 分钟（7个小时20分钟）
