### ISSUE TITLE
连taos-tools都编译不过，在ubuntu22上，无语

### ISSUE THREAD

**Issue by lld1995** [taosdata/taos-tools#688]
![image](https://github.com/taosdata/taos-tools/assets/17978390/06746ebf-eb25-41b0-854f-9ae154a82845)

**Comment by sangshuduo** [comment]
都不看readme吗？

**Comment by lld1995** [comment]
> 

readme 写的都装了

**Comment by lld1995** [comment]
甚至把avro dev什么的全都装了

**Comment by sangshuduo** [comment]
![image](https://github.com/taosdata/taos-tools/assets/825729/095e7ebe-8b49-473d-9eb0-6ea165653575)

**Comment by lld1995** [comment]
> ![image](https://user-images.githubusercontent.com/825729/255133354-095e7ebe-8b49-473d-9eb0-6ea165653575.png)

adminadmin@adminadmin-virtual-machine:~/disk2/taos-tools$ cd build/
adminadmin@adminadmin-virtual-machine:~/disk2/taos-tools/build$ ll
total 68
drwxrwxr-x  6 adminadmin adminadmin  4096 Jul 21 02:59 ./
drwxrwxr-x 13 adminadmin adminadmin  4096 Jul 21 02:54 ../
drwxrwxr-x  5 adminadmin adminadmin  4096 Jul 21 02:59 build/
-rw-rw-r--  1 adminadmin adminadmin 19567 Jul 21 02:59 CMakeCache.txt
drwxrwxr-x  5 adminadmin adminadmin  4096 Jul 21 03:04 CMakeFiles/
-rw-rw-r--  1 adminadmin adminadmin  2132 Jul 21 02:59 cmake_install.cmake
-rw-r--r--  1 adminadmin adminadmin  3195 Jul 21 02:59 CPackConfig.cmake
-rw-r--r--  1 adminadmin adminadmin  3650 Jul 21 02:59 CPackSourceConfig.cmake
drwxrwxr-x  8 adminadmin adminadmin  4096 Jul 21 02:59 deps/
-rw-rw-r--  1 adminadmin adminadmin 10612 Jul 21 02:59 Makefile
drwxrwxr-x  3 adminadmin adminadmin  4096 Jul 21 02:59 src/
adminadmin@adminadmin-virtual-machine:~/disk2/taos-tools/build$ cmake ..
 Enabled deflate codec 
 Enabled snappy codec 
 Enabled lzma codec 
 jansson found 
-- deps' cmake detected current OS is ubuntu
-- The current platform x86_64 is detected
-- The current platform is amd64
-- Set CPUTYPE to x64
Found VERSION file

taosdump last tag: 2.5.2
taosdump commit: 76ad294
taosdump status: 

taosBenchmark last tag: 3.2.2
taosBenchmark commit: 76ad294
taosBenchmark status: 

Current system is: Linux
-- The current OS is ubuntu
 RELEASE mode use static avro library to link for release 
Compiler is: GNU, version: 11.3.0
-- src's cmake detected current OS is ubuntu
-- libatomic.a path: /usr/lib/gcc/x86_64-linux-gnu/11/libatomic.a
libstdc++.a path:/usr/lib/gcc/x86_64-linux-gnu/11/libstdc++.a
libza path:/usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu/libz.a
-- Configuring done
-- Generating done
-- Build files have been written to: /home/adminadmin/disk2/taos-tools/build
adminadmin@adminadmin-virtual-machine:~/disk2/taos-tools/build$ make
[ 10%] Built target deps-jansson
[ 12%] Performing configure step for 'apache-avro'
CMake Error at CMakeLists.txt:39 (message):
  Cannot determine Avro version number


-- Configuring incomplete, errors occurred!
See also "/home/adminadmin/disk2/taos-tools/build/deps/avro/src/apache-avro-build/CMakeFiles/CMakeOutput.log".
make[2]: *** [deps/CMakeFiles/apache-avro.dir/build.make:92: deps/avro/src/apache-avro-stamp/apache-avro-configure] Error 1
make[1]: *** [CMakeFiles/Makefile2:211: deps/CMakeFiles/apache-avro.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
adminadmin@adminadmin-virtual-machine:~/disk2/taos-tools/build$

**Comment by sangshuduo** [comment]
拉一个全新的 2204 Docker 镜像，进入容器内 clone 代码编译，完全没有问题

docker run -dit ubuntu:22.04

![image](https://github.com/taosdata/taos-tools/assets/825729/384a39f1-fe8c-4613-9027-937f5022ffe0)

**Comment by lld1995** [comment]
找到问题原因了，脚本权限的问题，拷贝过来的时候，权限掉了
